version: '3.5'

services:
  deep-learning-image:
    runtime: nvidia
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    volumes:
      - ./basin:/basin/basin
    command: ["jupyter", "lab", "--port=8888", "--no-browser", "--ip=0.0.0.0", "--allow-root"]